menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/stormluke
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: stormluke-preferences
duoshuo:

# Analytics
# google-analytics:
ga: UA-60486509-1

# Copyright Infomation
startyear: 2012
